/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef report_self_CONSTANTS_H
#define report_self_CONSTANTS_H

#include "report_self_types.h"

namespace mooon {

class report_selfConstants {
 public:
  report_selfConstants();

};

extern const report_selfConstants g_report_self_constants;

} // namespace

#endif
