/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "db_proxy_types.h"

#include <algorithm>

namespace mooon { namespace db_proxy {

}} // namespace
