/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef db_proxy_CONSTANTS_H
#define db_proxy_CONSTANTS_H

#include "db_proxy_types.h"

namespace mooon { namespace db_proxy {

class db_proxyConstants {
 public:
  db_proxyConstants();

};

extern const db_proxyConstants g_db_proxy_constants;

}} // namespace

#endif
