/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "db_proxy_constants.h"

namespace mooon { namespace db_proxy {

const db_proxyConstants g_db_proxy_constants;

db_proxyConstants::db_proxyConstants() {
}

}} // namespace

